# Generated by Django 2.1.15 on 2021-11-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0031_cassette_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='No requiere armado'),
        ),
        migrations.AddField(
            model_name='slide',
            name='hidden_message',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
