# Generated by Django 3.2.7 on 2021-12-20 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0032_auto_20211102_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processunit',
            name='case_process',
        ),
        migrations.RemoveField(
            model_name='processunit',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='treeprocess',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='treeprocess',
            name='process',
        ),
        migrations.RemoveField(
            model_name='treeprocess',
            name='tree',
        ),
        migrations.AlterModelOptions(
            name='process',
            options={},
        ),
        migrations.RemoveField(
            model_name='process',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='process',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='process',
            name='name',
        ),
        migrations.RemoveField(
            model_name='process',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='process',
            name='done_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='sample_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.sampleexams'),
        ),
        migrations.AddField(
            model_name='process',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Morfometria'), ('2', 'Registro de imágenes macro'), ('3', 'Toma de Rx'), ('4', 'Derivación al laboratorio')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='unit_organ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.organunit'),
        ),
        migrations.DeleteModel(
            name='CaseProcessTree',
        ),
        migrations.DeleteModel(
            name='ProcessUnit',
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
        migrations.DeleteModel(
            name='TreeProcess',
        ),
    ]
