# Generated by Django 3.2.7 on 2021-12-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0033_auto_20211220_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Morfometria'), (2, 'Macro'), (3, 'Rx'), (4, 'Derivacion Laboratorio')]),
        ),
    ]
