# Generated by Django 3.2.7 on 2021-12-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0034_alter_process_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='sample_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='backend.sampleexams'),
        ),
        migrations.AlterField(
            model_name='process',
            name='unit_organ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='backend.organunit'),
        ),
    ]
