# Generated by Django 3.2.7 on 2022-02-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0019_attachment_finalreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='path',
            field=models.FileField(upload_to='', verbose_name='attachments'),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to='', verbose_name='reviews'),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='path',
            field=models.FileField(upload_to='', verbose_name='reports'),
        ),
    ]
