# Generated by Django 3.2.7 on 2022-05-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0151_auto_20220323_1042'),
        ('review', '0020_auto_20220208_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisGrouper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Grouper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ManyToManyField(related_name='groups', through='review.AnalysisGrouper', to='review.Analysis')),
                ('entryform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.entryform')),
            ],
        ),
        migrations.AddField(
            model_name='analysisgrouper',
            name='grouper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.grouper'),
        ),
    ]
