# Generated by Django 2.1.15 on 2021-10-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210610_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signing',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Firma'),
        ),
    ]
