# Generated by Django 3.2.7 on 2023-06-29 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0158_automatic_report'),
        ('mb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='organ_unit',
            field=models.ManyToManyField(through='mb.PoolOrganUnit', to='backend.OrganUnit'),
        ),
        migrations.AlterField(
            model_name='poolorganunit',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mb.pool'),
        ),
    ]
