# Generated by Django 2.1.15 on 2021-09-27 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('backend', '0128_auto_20210824_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='id_modelo',
        ),
        migrations.RemoveField(
            model_name='log',
            name='log_date',
        ),
        migrations.RemoveField(
            model_name='log',
            name='log_type',
        ),
        migrations.RemoveField(
            model_name='log',
            name='modelo',
        ),
        migrations.AddField(
            model_name='log',
            name='activity',
            field=models.CharField(choices=[('C', 'Create'), ('U', 'Update'), ('D', 'Delete')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='log',
            name='description',
            field=models.CharField(default='', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='logged_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LogType',
        ),
    ]
