# Generated by Django 2.1.15 on 2021-10-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0130_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='company_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
