# Generated by Django 2.1.15 on 2021-11-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0131_auto_20211013_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='pais'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type_customer',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tipo de Cliente'),
        ),
    ]
