# Generated by Django 2.1.15 on 2021-11-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0132_auto_20211111_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='corporate_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='razon_social'),
        ),
    ]
