# Generated by Django 2.1.15 on 2021-11-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0133_customer_corporate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='larvalstage',
            name='name_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='specie',
            name='common_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='name_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
