# Generated by Django 3.2.7 on 2021-11-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0129_auto_20210910_1401'),
        ('backend', '0134_auto_20211119_1040'),
    ]

    operations = [
    ]
