# Generated by Django 3.2.7 on 2021-11-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0135_merge_0129_auto_20210910_1401_0134_auto_20211119_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisform',
            name='samples',
            field=models.ManyToManyField(related_name='analysis', to='backend.OrganUnit'),
        ),
    ]
