# Generated by Django 3.2.7 on 2021-12-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0135_auto_20211201_1540'),
        ('backend', '0136_analysisform_samples'),
    ]

    operations = [
    ]
