# Generated by Django 3.2.7 on 2021-12-30 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0137_merge_20211201_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisPreinvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samples_studied', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='analysisform',
            name='currency',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='moneda'),
        ),
        migrations.AddField(
            model_name='analysisform',
            name='exchange_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='tipo de cambio'),
        ),
        migrations.AddField(
            model_name='analysisform',
            name='unit_value',
            field=models.FloatField(blank=True, null=True, verbose_name='valor unitario'),
        ),
        migrations.CreateModel(
            name='Preinvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, verbose_name='folio')),
                ('date', models.DateField(verbose_name='fecha')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='monto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ManyToManyField(through='backend.AnalysisPreinvoice', to='backend.AnalysisForm')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preinvoices', to='backend.customer', verbose_name='cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, verbose_name='folio')),
                ('date', models.DateField(verbose_name='fecha')),
                ('observations', models.CharField(blank=True, max_length=120, null=True)),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='monto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='backend.customer', verbose_name='cliente')),
                ('preinvoices', models.ManyToManyField(related_name='invoices', to='backend.Preinvoice')),
            ],
        ),
        migrations.AddField(
            model_name='analysispreinvoice',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.analysisform'),
        ),
        migrations.AddField(
            model_name='analysispreinvoice',
            name='preinvoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.preinvoice'),
        ),
    ]
