# Generated by Django 3.2.7 on 2022-01-10 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0138_auto_20211230_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='es', max_length=4, verbose_name='idioma'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='sujeto'),
        ),
        migrations.AlterField(
            model_name='emailtemplateattachment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='backend.emailtemplate'),
        ),
    ]
