# Generated by Django 3.2.7 on 2022-01-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0139_auto_20220110_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisform',
            name='on_hold',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='analysisform',
            name='on_standby',
            field=models.DateTimeField(null=True),
        ),
    ]
