# Generated by Django 3.2.7 on 2022-01-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0140_auto_20220117_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='abreviacion'),
        ),
    ]
