# Generated by Django 3.2.7 on 2022-01-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0144_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisform',
            name='currency',
            field=models.CharField(blank=True, default='UF', max_length=6, null=True, verbose_name='moneda'),
        ),
    ]
