# Generated by Django 3.2.7 on 2022-01-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0145_alter_analysisform_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisform',
            name='currency',
            field=models.CharField(default='UF', max_length=6, verbose_name='moneda'),
        ),
    ]
