# Generated by Django 3.2.7 on 2022-03-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0148_auto_20220204_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='abreviacion'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='organ_type',
            field=models.IntegerField(choices=[(1, 'Órgano por sí solo'), (2, 'Conjunto de órganos'), (3, 'Órganos de un conjunto')], default=1, verbose_name='tipo'),
        ),
    ]
