# Generated by Django 3.2.7 on 2022-03-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0149_auto_20220318_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='analysis_preinvoices',
        ),
        migrations.AddField(
            model_name='invoice',
            name='preinvoices',
            field=models.ManyToManyField(related_name='invoices', to='backend.Preinvoice'),
        ),
    ]
