# Generated by Django 3.2.7 on 2022-05-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0151_auto_20220323_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisform',
            name='samples_charged',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
