# Generated by Django 3.2.7 on 2022-09-09 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0153_auto_20220606_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='inter_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PreinvoiceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vehice_preinvoice_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='preinvoice',
            name='attached_files',
            field=models.ManyToManyField(blank=True, to='backend.PreinvoiceFile'),
        ),
    ]
