# Generated by Django 3.2.7 on 2022-09-27 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0154_auto_20220909_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisform',
            name='manual_reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisform',
            name='manual_reopened_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
