# Generated by Django 3.2.7 on 2022-11-11 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0155_auto_20220927_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='laboratory_deadline',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='pathologist_deadline',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='review_deadline',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='AnalysisTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, default=None, null=True)),
                ('changeDeadline', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.analysisform', verbose_name='analysis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.exam', verbose_name='exam')),
                ('service_comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.servicecomment')),
                ('type_deadline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.typedeadline')),
            ],
        ),
    ]
