# Generated by Django 3.2.7 on 2023-07-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0159_AnalysisReport_add_correlative'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='etiological_diagnostic',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
