# Generated by Django 3.2.7 on 2023-08-11 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0160_etiological_diagnostic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.exam', verbose_name='exam')),
            ],
        ),
        migrations.CreateModel(
            name='MethodologyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='MethodologyImage')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=25, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('methodology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.methodology')),
            ],
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='methodology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.methodology'),
        ),
    ]
