# Generated by Django 3.2.7 on 2023-08-30 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0161_methodology'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='chargeable',
            field=models.BooleanField(default=True, verbose_name='cobrable'),
        ),
        migrations.AddField(
            model_name='exam',
            name='factor_HE',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='methodologyimage',
            name='methodology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.methodology'),
        ),
    ]
