# Generated by Django 3.2.7 on 2023-09-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0162_auto_20230830_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinvoice',
            name='pay_person',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
