# Generated by Django 3.2.7 on 2024-01-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0164_customer_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersource',
            name='type_of_water',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
